### ISSUE TITLE
connectApi.ts -> updatePresubscriptions sample

### ISSUE THREAD

**Issue by ranshe** [ARMmbed/mbed-cloud-sdk-javascript#217]
Can the presubscriptions example be updated to use a URI sample?
I think it's the one required parameter in https://cloud.mbed.com/docs/v1.2/service-api-references/connect-api.html#PresubscriptionArray

Also, if you can contrast that w/ addResourceSubscription, that would be even better.

**Comment by madchutney** [comment]
Hi Ran,

We are looking at the subscriptions / presubscriptions so should hopefully be able to make some improvements.

Graham

**Comment by ranshe** [comment]
Come to think of it, if you can do a fully working example that mimics what we have in https://cloud.mbed.com/docs/v1.2/service-api-references/connect-api.html#subscriptions, that's even better

**Comment by ranshe** [comment]
Is there a specific (with dates) plan for this?

--Ran (sent from mobile)

**Comment by ranshe** [comment]
1. If you look @ https://cloud.mbed.com/docs/v1.2/service-api-references/connect-api.html#subscriptions and expand PUT /v2/subscriptions, there's a sample there using curl.
The request is to show how to achieve that same thing using js.

2. When looking @ https://cloud.mbed.com/docs/v1.2/service-api-references/connect-api.html#PresubscriptionArray, you see that uri is required parameter.
The request is to have the example reflect that

**Comment by alexl0gan** [comment]
The PresubscriptionArray hasn't been defined properly in the swagger so it has no attributes. You're looking at the Resource model. The example for PUT v2/subscriptions shows what the presubscription array looks like.

**Comment by ranshe** [comment]
So again - is there a date attached to this?
Thanks

**Comment by alexl0gan** [comment]
@ranshe version 1.2.9 has now been released. 

Please see https://github.com/ARMmbed/mbed-cloud-sdk-javascript/blob/master/examples/node/webhook-subscriptions.js#L45 for a basic presubscription/subscription example. 

Also https://github.com/ARMmbed/mbed-cloud-sdk-javascript/blob/master/examples/node/subscribe.js#L42 has further examples.

These are new features that are trying to abstract away the confusion between subscriptions/presubscriptions so any feedback you have as to the usability of this would be very helpful.
