### ISSUE TITLE
How do you subscribe to all notifications from any device of yours?

### ISSUE THREAD

**Issue by mbanders** [ARMmbed/mbed-cloud-sdk-javascript#228]
Hi,

Our goal: to set a callback url and subscribe to all notifications from any device of mine. We only have two devices, so subscribing to all is fine.

I've looked at two things:

* subscribe.js: https://github.com/ARMmbed/mbed-cloud-sdk-javascript/blob/a17302080ea6616ab43af994536930d92895dd09/examples/node/subscribe.js
* docs: https://cloud.mbed.com/docs/v1.2/mbed-cloud-sdk-javascript/classes/connectapi.html#addresourcesubscription

So now I have code that looks like this:
```js
var connect = new MbedCloudSDK.ConnectApi({apiKey: my_mbed_key,
                                           host: "https://api.us-east-1.mbedcloud.com"
    });
// Set callback url
connect.updateWebhook(my_url);
// To Do: subscribe to everything, how?
```

From the example file `subscribe.js` I see a "observer" being created, but I don't see that described in the docs. Can you clarify on how we might do what we want here?

**Comment by alexl0gan** [comment]
Hi,

There appears to be some issue with the generation of the subscribe module docs and an defect has been raised [here](https://jira.arm.com/browse/IOTSTOOL-1123)

Currently you can only use the subscribe module to listen for device events, such as registrations and deregistrations. However we are in the process of adding support for subscriptions as well and that should be released next week.

Until then, device subscriptions are only set at a resource level, so the solution would be to add a subscription for all resources on a device by looping through that devices resources. This isn't ideal because only the payload is returned so you can't differentiate between the resources that sent the value. The code below would achieve this. 

```
var notifyFunction = (data) => { //do something with notification };

connect.listConnectedDevices()
.then(devices => {
    devices.forEach(device => {
        device.listResources()
        .then(resources => {
            resources.forEach(resource => {
                device.addResourceSubscription(resource.path, notifyFunction);
            });
        });
    });
});
```

When the subscribe module is completed (interface subject to change), you'll be able to do

```
var observer = connect.subscribe.resourceValueChanges( { deviceId = "myId" } );
observer.addCallback((data) => {
    // do something with data
    if (data.path === "/3200/0/5501") {
         // button press
    }
});
```
Where the data sent back contains the payload, deviceId and path. Under the hood, this will create both a subscription and presubscription all resources on that device.

**Comment by mbanders** [comment]
Thanks, I'll be interested to see the docs, and also the new subscribe module when it's done. I'd like to do it that way.

In the meantime we tried your first suggestion, but we're getting an error:

```js
const MbedCloudSDK = require('mbed-cloud-sdk')
const my_mbed_key = "ak_1MD..."

var connect = new MbedCloudSDK.ConnectApi({apiKey: my_mbed_key,
					   host: "https://api.us-east-1.mbedcloud.com"
					  })

connect.listConnectedDevices().then(devices => {
    devices.forEach(device => {
	// do nothing
    })
})
```

Running the above code:

```sh
$ node index.js
(node:1029) UnhandledPromiseRejectionWarning: TypeError: devices.forEach is not a function
    at connect.listConnectedDevices.then.devices (/home/pi/Documents/mbed_play/index.js:12:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:1029) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1029) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

We are using `node v9.10.1` and `mbed-cloud-sdk 1.2.8`.

**Comment by mbanders** [comment]
Ok got it now. For any future person interested here's a working example:

```js
const MbedCloudSDK = require('mbed-cloud-sdk')

const my_mbed_key = "ak_1MD..."

var connect = new MbedCloudSDK.ConnectApi({
    apiKey: my_mbed_key,
    host: "https://api.us-east-1.mbedcloud.com"
})

connect.listConnectedDevices().then(devices => {
    devices.data.forEach(device => {
        device.listResources().then(resources => {
            console.log("Device " + device.id + " has resources:")
            console.log(resources.map(r => r.path))
            // can also loop over resources and do addResourceSubscription
        });
    })
})
```

Thanks for your help. And we will keep an eye out for when the subscribe module is completed.

**Comment by mbanders** [comment]
PS: For anyone that has questions about the documentation where exactly should we post questions, here on github? Or should we email someone? Or?

For example we have questions about https://cloud.mbed.com/docs/v1.2/mbed-cloud-sdk-javascript/interfaces/devicelistoptions.html#filter

**Comment by alexl0gan** [comment]
Don't look at the documentation at that link. cloud.mbed.com/docs/v1.2 is no longer being updated. https://cloud.mbed.com/docs/latest/mbed-cloud-sdk-javascript/interfaces/devicelistoptions.html#filter is the correct place to look. 

As for questions, if you're on slack, the #mbed-cloud-sdk is a good place to ask general questions. Issues here are ok but sometimes it can take a bit if time before we notice they've been raised. You can raise a ticket on our Jira board, IOTSTOOL, and that will be looked at faster.
