### ISSUE TITLE
[DOC] cannot run proxy example

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/mbed-cloud-sdk-javascript#409]
The instruction for the example [here](https://github.com/ARMmbed/mbed-cloud-sdk-javascript/tree/master/examples#proxy) described:

>To start the proxy server, run the npm start command from the root of the project:
>
>```bash
>> npm start
>```

However, I got error below:
```PowerShell
PS X:\mbed-cloud-sdk-javascript> npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\toywat01\AppData\Roaming\npm-cache\_logs\2019-05-29T04_12_05_166Z-debug.log
PS X:\mbed-cloud-sdk-javascript>
```

This should be `npm run start-proxy` since the package.json only has `start-proxy` entry [here](https://github.com/ARMmbed/mbed-cloud-sdk-javascript/blob/master/package.json#L58).
```PowerShell
PS X:\mbed-cloud-sdk-javascript> npm run start-proxy

> mbed-cloud-sdk@2.2.0 start-proxy X:\mbed-cloud-sdk-javascript
> node examples/proxy/server.js

Proxy server listening at http://localhost:8080
```

**Comment by alexl0gan** [comment]
Well spotted! I've updated the examples readme.
