### ISSUE TITLE
ConnectApi.getResourceValue() doesn't work correctly after v2.0.3

### ISSUE THREAD

**Issue by coisme** [ARMmbed/mbed-cloud-sdk-javascript#447]
# Issue

`ConnectApi.getResourceValue()` doesn't work correctly after v2.0.3

# Environment

macOS Mojave Version 10.14.5

Node.js
```
$ node --version
v10.15.3
```

Hardware: K64F running [CONNECT GUIDE](https://os.mbed.com/guides/connect-device-to-pelion/)'s program

# Steps to reproduce

Create a working directory.
```
$ mkdir pdm_sample
$ cd pdm_sample
```

Import `mbed-cloud-sdk`
```
$ npm install mbed-cloud-sdk
```
This installs the latest mbed-cloud-sdk, v2.3.1 today.

## Test Script
This script obtains resource value from the button count resource `/3200/0/5501` from the connected device. Created based on example code on API reference. Replace `MY_API_KEY` and `MY_DEVICE_ID` with yours.
```
var PelionDMSDK = require("mbed-cloud-sdk");

var connect = new PelionDMSDK.ConnectApi({
    apiKey: "MY_API_KEY",
    startNewNotification: true,
});

var deviceId = "MY_DEVICE_ID";
var resourceURI = "/3200/0/5501";
connect.getResourceValue(deviceId, resourceURI)
.then(data => {
    console.log(data);
    connect.stopNotifications();
})
.catch(error => {
    console.log(error);
});
```

### Expected Result
Returns the button count value corresponds to the resource value of `/3200/0/5501`.
```
0
```

### Result in v2.0.2
```
$ node index.js
0
```
Returns as expected.

### Result in v2.0.3
```
$ node index.js
{ id: '15622238962437593',
  status: 200,
  payload: 'MA==',
  ct: 'text/plain',
  'max-age': 0 }
  ```
See the raw JSON object.

### Result in v2.2.0
```
$ node index.js
```
Nothing appeared.

### Result in v2.3.1
```
$ node index.js
```
Nothing appeared.

**Comment by alexl0gan** [comment]
The problem is in the initialisation of the connectApi. 

When you initialise the connectApi, there is no configuration option `startNewNotification`. It should be 

```
const connect = new ConnectApi({
    apiKey: "MY_API_KEY",
    autostartNotifications: true,
});
```

The reason your example worked pre version 2.2.0 was because the `autostartNotifications` option was only introduced at this version, and it defaults too false.

I was able to get this code working with the latest version.

```
import { ConnectApi } from "mbed-cloud-sdk";

const connect = new ConnectApi({
    autostartNotifications: true,
});

const main = async () => {

    try {
        const value = await connect.getResourceValue("016ac...", "/3200/0/5501");
        console.log(value);
    } catch (e) {
        throw e;
    }

    process.exit();
};

main();

```

To avoid issues like this, I would suggest trying out Typescript as it would prevent you from setting an incorrect key is this way.

**Comment by coisme** [comment]
@alexl0gan Thank you for quick reply.

I tried your code with mbed-cloud-sdk v2.3.1. I got an error:
```
$ node index.js
/Users/osakoi01/mbed/20190702_exercise/Service_SDK/index.js:1
(function (exports, require, module, __filename, __dirname) { import { ConnectApi } from "mbed-cloud-sdk";
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

```
$ npm list --depth=0
service_sdk2@1.0.0 /Users/osakoi01/mbed/20190702_exercise/Service_SDK2
└── mbed-cloud-sdk@2.3.1
```

Node.js
```
node --version
v10.15.3
```

Do I miss something?

**Comment by alexl0gan** [comment]
I wrote that in Typescript, so you get the es6 import style for free. The following works in a .js file, node version 10.16.0

```
const sdk = require("mbed-cloud-sdk");

const connect = new sdk.ConnectApi({
    autostartNotifications: true,
});
```

**Comment by coisme** [comment]
Thanks! I tried this code with `node v10.16.0` and `mbed-cloud-sdk v2.3.1`.
```
const sdk = require("mbed-cloud-sdk");

const connect = new sdk.ConnectApi({
    autostartNotifications: true,
});

const main = async () => {

    try {
        const value = await connect.getResourceValue("016bb12e735a0000000000010010003b", "/3200/0/5501");
        console.log(value);
    } catch (e) {
        throw e;
    }

    process.exit();
};

main();
```

I got the result:
```
$ n use 10.16.0 index2.js
{ id: '15622474592643745',
  status: 200,
  payload: 'MA==',
  ct: 'text/plain',
  'max-age': 0 }
```
JSON object appears. Is this expected result of getResourceValue()?

**Comment by alexl0gan** [comment]
No, you should get the decoded body. When I run this I get the resource value as expected. Can we switch to email so I can investigate further?

**Comment by coisme** [comment]
Sure. No problem.

**Comment by coisme** [comment]
The issue cannot be reproduced anymore.
