### ISSUE TITLE
Uncaught TypeError: MbedCloudSDK.DeviceDirectoryApi is not a constructor

### ISSUE THREAD

**Issue by GQMai** [ARMmbed/mbed-cloud-sdk-javascript#457]
Hi,

When running examples in Proxy mode, I met the following error in device management page.
![image](https://user-images.githubusercontent.com/5309276/62039372-2889c980-b22a-11e9-8244-cbac6de641ce.png)

Please help.

Thanks,
Nic

**Comment by alexl0gan** [comment]
Dealt with in #460
